city_codes = {
    "Mumbai": "BOM",
    "Delhi": "DEL",
    "Bangalore": "BLR",
    "Hyderabad": "HYD",
    "Ahmedabad": "AMD",
    "Chennai": "MAA",
    "Kolkata": "CCU",
    "Pune": "PNQ",
    "Jaipur": "JAI",
    "Lucknow": "LKO",
    "Kanpur": "KNP",
    "Nagpur": "NAG",
    "Indore": "IDR",
    "Thane": "THA",
    "Bhopal": "BHO",
    "Visakhapatnam": "VTZ",
    "Ludhiana": "LUH",
    "Agra": "AGR",
    "Aligarh": "ALG",
    "Varanasi":"VNS",
    "Banaras":"VNS",
    "Mathura": "MTR",
    "Jhansi": "JHS",
    "Rampur": "RMP",
    "Gorakhpur": "GKP",
    "Lucknow": "LKO",
    "Prayagraj ": "PRJ",
    "Allahabad": "PRJ",
    "Rajpura": "RJP",
    "Saharanpur": "SRE",
     "Ghaziabad": "GZB",
     "Faridabad": "FBD",
     "Ahmedabad, Gujarat": "AMD",
     "Kolkata": "KOT"
}
